phase: 0
num_processes: 48
ts_per_iter: 50000
ppo_epochs: 3
ppo_minibatch_size: 50000
ppo_ent_coef: 0.01
policy_net_lr: 2.0e-4
critic_net_lr: 2.0e-4
save_every_ts: 250_000
render: true
render_delay: 0
timestep_limit: 1000000000
exp_buffer_size_multiple: 3
log_to_wandb: true
load_wandb: true
wandb_run_name_prefix: PPO-p
wandb_project_name_prefix: v2_phase
checkpoint_save_folder_prefix: data/checkpoints/p
checkpoint_load_path: null
network_shape:
  - 2048
  - 2048
  - 1024
  - 1024
